services:
  - type: web
    name: teacher-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    runtime: python
